name: Unit Test & End to End
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node ${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Jest Unit Testing
        run: npm test
        
