name: Upgrade Compability Check
on: push

jobs:
  upgrade-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
        next: [canary, latest]

    name: Upgrade to NODE ${{matrix.node}} NEXT ${{matrix.next}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node ${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install ${{matrix.next}} version
        run: npm install next@${{matrix.next}} react@${{matrix.next}} react-dom@${{matrix.next}} eslint-config-next@${{matrix.next}}

      - name: Install dependencies on NODE ${{matrix.node}} in NEXT ${{matrix.next}}
        run: npm install

      - name: Run tests on NODE ${{matrix.node}} in NEXT ${{matrix.next}}
        run: npm test

      - name: Run build on NODE ${{matrix.node}} in NEXT ${{matrix.next}}
        run: npm run build
